name: Build Prisma Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Prisma version to build (ex. 5.1.0)"
        required: true
        type: string
      tag:
        description: "Docker version tag to push (ex. 5.1.x)"
        required: true
        type: string

jobs:
  build-amd64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/diced/prisma-binaries:${{ github.event.inputs.tag }}-amd64
          build-args: |
            PRISMA_VERSION=${{ github.event.inputs.version }}
  build-arm64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64
          tags: ghcr.io/diced/prisma-binaries:${{ github.event.inputs.tag }}-arm64
          build-args: |
            PRISMA_VERSION=${{ github.event.inputs.version }}
  ammend-builds:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull images
        run: |
          docker pull ghcr.io/diced/prisma-binaries:${{ github.event.inputs.tag }}-amd64
          docker pull ghcr.io/diced/prisma-binaries:${{ github.event.inputs.tag }}-arm64
      - name: create manifest & ammend
        run: |
          docker manifest create ghcr.io/diced/prisma-binaries:${{ github.event.inputs.tag }} \
            --amend ghcr.io/diced/prisma-binaries:${{ github.event.inputs.tag }}-amd64 \
            --amend ghcr.io/diced/prisma-binaries:${{ github.event.inputs.tag }}-arm64
      - name: push manifest
        run: |
          docker manifest push ghcr.io/diced/prisma-binaries:${{ github.event.inputs.tag }}
